spring.application.name=limits-config
spring.config.import=optional:configserver:http://localhost:8888
limits-service.minimum=3
limits-service.maximum=800
spring.profiles.active=qas
spring.cloud.config.profile=qas