spring.application.name=learn-springboot-framework
logging.level.org.springframework=debug
spring.profiles.active=uat

currency.url=http://default.com
currency.username=defaultuser
currency.password=defaultpwd

management.endpoints.web.exposure.include=*