spring.application.name=naming-server
server.port = 8761

eureka.client.register-with-eureka=false 
#this property tells that i am a naming server and you do not need to register yourself
eureka.client.fetch-registry=false
#this property tells do not fetch all the registered services. clients will register with you.