spring.application.name=restful-web-services
logging.level.org.springframework=INFO
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb123
spring.jpa.defer-datasource-initialization = true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true